"""Add positions_to_fill to JobPosting

Revision ID: 2aa8c91debe9
Revises: 
Create Date: 2025-08-01 00:46:35.753814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2aa8c91debe9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_posting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('positions_to_fill', sa.Integer(), nullable=False,  server_default='1'))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_upload_date')
        batch_op.drop_column('uploads_today')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uploads_today', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('last_upload_date', sa.DATE(), autoincrement=False, nullable=True))

    with op.batch_alter_table('job_posting', schema=None) as batch_op:
        batch_op.drop_column('positions_to_fill')

    # ### end Alembic commands ###
