"""Add daily upload tracking to User model

Revision ID: 659c3865bacf
Revises: 2aa8c91debe9
Create Date: 2025-08-07 15:15:21.966646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '659c3865bacf'
down_revision = '2aa8c91debe9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uploads_today', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_upload_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_upload_date')
        batch_op.drop_column('uploads_today')

    # ### end Alembic commands ###
